name: Enviar Datos a Notion

on: 
  workflow_dispatch:
  repository_dispatch:

jobs:
  enviar_a_notion:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar Datos a Notion
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        run: |
          curl -X POST "https://api.notion.com/v1/pages" \
          -H "Authorization: Bearer $NOTION_API_TOKEN" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "parent": { "page_id": "'"$NOTION_PAGE_ID"'" },
            "properties": {
              "Title": {
                "title": [
                  {
                    "text": {
                      "content": "Ejemplo desde GitHub Action"
                    }
                  }
                ]
              }
            }
          }'
